### ISSUE TITLE
[Feature Request] Better signal the user if "delete files from storage" is checked

### ISSUE THREAD

**Issue by ericswpark** [WDaan/VueTorrent#1010]
I accidentally deleted a completed download today with the following dialog:

![Screenshot 2023-07-30 at 12 40 17 AM](https://github.com/WDaan/VueTorrent/assets/13326074/828e2e8e-1343-4e52-8207-6600e414cbdf)

It looks obvious now that I look at it, but back when I looked at that dialog I couldn't tell if the checkbox was checked or not, because the checked color is dark like the background. I assumed that the "Delete" button was red because it is a potentially destructive action (if you don't have the torrent file then it's hard to add it back), not because the checkbox was checked.

It would be great if the UI could be updated with the following:
- Better checked checkbox color to differentiate between background color
- Have a "This will DELETE all files downloaded with this torrent!" warning text show up in red underneath the checkbox if the checkbox is checked, and disappear if it isn't. Sort of like this:
![Screenshot 2023-07-30 at 12 45 14 AM](https://github.com/WDaan/VueTorrent/assets/13326074/f0a94032-dc94-4609-b046-2dbe03a3c966)

**Comment by herrenP** [comment]
I think the appearance of a checked checkbox need to improve. It's not clear enough that's it's selected. The current colors of it makes it look almost as if it's indicating a default value rather than what the user has currently put it in. The button is clear, but the checkbox isn't. I almost don't even notice the checkbox at all because of its current color scheme.

**Comment by Larsluph** [comment]
I agree that the contrast can be improved. I'll keep that in mind when reworking the color scheme for the v2.
