### ISSUE TITLE
[Bug] Getting login screen even when logged in

### ISSUE THREAD

**Issue by SinTan1729** [WDaan/VueTorrent#1285]
Even if I'm logged in, I get a login screen while accessing the VueTorrent page. Going to the same address again fixes it. I don't get asked for logins across reloads.

[Here's a screen recording.](https://streamable.com/ympfhc)

**Comment by Larsluph** [comment]
This can happen sometimes. We can't replicate this bug so it's kinda hard to fix. If you have any idea, we'll take them!

**Comment by WDaan** [comment]
I run into this as well. Even more so on PWA, we haven't been able to come up with a fix yet though 🙁 

Thanks for reporting!

**Comment by zbikk** [comment]
can replicate, even with 0.0.0.0/0 bypassed i still get the login screen everytime, doesn't happen on native web ui.

**Comment by Larsluph** [comment]
@zbikk If you have reliable reproduction steps (preferably from clean setup), we'll be happy to hear from you. It will greatly decrease the time required to fix it!

**Comment by zbikk** [comment]
https://i.imgur.com/oanmDiL.mp4

as you can see from the video above when at the login screen if i press on anything really and then return it gives me the torrent screen so it's not an authorization issue and rather an issue with the login screen itself. as for reproduction steps i can't give you much except that it happens on clean installs as well, here are my web ui settings: 
![image](https://github.com/WDaan/VueTorrent/assets/145393776/a4a153ff-d6f7-4a78-8043-b77b7154d924)

**Comment by Larsluph** [comment]
@zbikk Do you know if it also happens in a clean browser environment (in private mode for example)?

**Comment by SinTan1729** [comment]
I just tested. It does happen in private mode for Firefox. But it doesn't seem to happen at all in Chromium (both incognito and otherwise). But it happens in Chromium based browsers on Android.

**Comment by plexecutor** [comment]
I setup VueTorrent yesterday and noticed this issue, but only when connecting via reverse proxy. I use Nginx Proxy Manager and when I access via my public domain name for the first time during a new browsing session using Chromium based browsers (Edge, Chrome), instead of seeing my basic auth prompt that NPM is configured for, I get the VueTorrent/qBittorrent login prompt--which will not accept my credentials. Reloading the page prompts for NPM basic auth and then bypasses VueTorrent/qBittorrent auth using the whitelisted IP. Strangely, this is not a problem at all if I use incognito mode. Using the native qBittorrent webui sans VueTorrent, it behaves as expected.

**Comment by Beet4** [comment]
I can confirm this as well on Firefox Desktop. It started happening after the Vue 3 update, before that it worked without issues.
