### ISSUE TITLE
[Featuer Request] Set the position of the Add Torrents button

### ISSUE THREAD

**Issue by CleverMod** [WDaan/VueTorrent#1409]
It is recommended to move the "Add Torrents" button to the top. Currently, each addition requires sliding to the bottom to click on it
![微信截图_20231213102247](https://github.com/WDaan/VueTorrent/assets/24726890/983664f0-ec59-411c-a109-322e51069be5)

**Comment by tainewoo** [comment]
I think it's a good suggestion, to reduce scroll actions for uers.
Mostly I use RSS to add torrents automatically, but if we add torrents manually, this change will help users to improve the efficiency of adding the torrent, because some users will not want to modify the detailed options when adding a torrent.

**Comment by Larsluph** [comment]
I already tried having the card actions to be fixed without success. I need to dig in the vuetify doc to see if there's a built-in way to do it
