### ISSUE TITLE
[Feature Request]: ”REGISTER MAGNET LINKS“ opens in a new tab in the foreground

### ISSUE THREAD

**Issue by chuwza** [WDaan/VueTorrent#1434]
### Description

Hi, currently this feature opens as an override of the current tab, which I think is unreasonable😂.

As currently designed, the torrent search site will be got overlaid by Vuetorrent's webpage, and I won't be able to download the second and third files from the torrent search site (as shown in the picture)
![屏幕截图(349) (中)](https://github.com/WDaan/VueTorrent/assets/30049891/971fc02d-5717-4529-96f7-05ee003b48c3)

With the current design, I need to research and go to thepiratebay again after one download, and then download the second file, the third file, It's too much trouble😥.

I think the torrent search page is the most basic thing for a BT user, and that should never be got overlaid!😣

### Describe the solution you'd like

I think the solution is very simple, just add a switch for this feature (as shown in the picture).
![IMG_20231231_183822](https://github.com/WDaan/VueTorrent/assets/30049891/bfaed9d4-58fe-480a-b05e-a94310030b44)

### Describe alternatives you've considered

There is no alternatives at all, I can only hope that you can add a switch, thank you very much!😄

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
Looking at the [source](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler#syntax), I don't think it's possible to change that. Maybe try to open the magnet in another tab instead of just opening it ?

**Comment by chuwza** [comment]
> open the magnet in another tab

Hello, So how to "open the magnet in another tab"? Right mouse click and then click open in new tab? I mean, that's what I'm hoping Vuetorrent will do.

**Comment by Larsluph** [comment]
> that's what I'm hoping Vuetorrent will do.

As said earlier, the browser protocol handler API doesn't provide a way to change that behavior. Opening a link in another tab is done by the website "hosting" the link, in your case the tracker itself.

If you don't want to think about that, you should find plenty of extensions and even browser settings for some that can do it for you.

Pro tip: On desktop, you can <kbd>ctrl</kbd> + <kbd>click</kbd> or <kbd>scroll click</kbd> on a link to open it in a new tab.

Also a workaround for that problem is by using the Drag-and-Drop already implemented in VueTorrent to open your link. Simply open your VueTorrent instance in a new window and drag any link you want in that window, it will automatically add the link to the queue just like the current magnet handler.

**Comment by chuwza** [comment]
> > that's what I'm hoping Vuetorrent will do.
> 
> As said earlier, the browser protocol handler API doesn't provide a way to change that behavior. Opening a link in another tab is done by the website "hosting" the link, in your case the tracker itself.
> 
> If you don't want to think about that, you should find plenty of extensions and even browser settings for some that can do it for you.
> 
> Pro tip: On desktop, you can + or on a link to open it in a new tab.ctrlclickscroll click
> 
> Also a workaround for that problem is by using the Drag-and-Drop already implemented in VueTorrent to open your link. Simply open your VueTorrent instance in a new window and drag any link you want in that window, it will automatically add the link to the queue just like the current magnet handler.

I think "Drag-and-Drop" is a good way to go, In a sense my problem was solved. Thank you very much!😄
