### ISSUE TITLE
Torrent title decode

### ISSUE THREAD

**Issue by ArabCoders** [WDaan/VueTorrent#239]
Hi is it possible to URL decode the torrent title? right now it's URL encoded showing %'s in the title for example

```
Show+Title+%282005%29+Season+1+S01+%2B+Extras+%281080p 
```

instead of 
```
Show Title (2005) Season 1 S01 + Extras 1080p
```

**Comment by m4ximuel** [comment]
Do you mean, the torrent title displays the URL code? I guess that original data is URL encoded. Repetition of encoding and decoding that is not suitable for the purpose may damage the original.
However, there is an idea worth putting url encoding and ansi encoding in 'renameModal' to solve the human error that often exists.

**Comment by ArabCoders** [comment]
![image](https://user-images.githubusercontent.com/1621552/115819046-c19d4280-a406-11eb-9b5c-72d3f0877d87.jpeg) this is how the title is displayed ATM.

**Comment by m4ximuel** [comment]
@ArabCoders Yes I caught it. I mean, it's a human error. The uploader entered the encoded text.
Could you check how it is displayed in the qbittorrent basic web ui or program ui? If going through the url encoding process is the current standard, I will proceed with the PR work.

**Comment by ArabCoders** [comment]
> @ArabCoders Yes I caught it. I mean, it's a human error. The uploader entered the encoded text.
> 
> Could you check how it is displayed in the qbittorrent basic web ui or program ui? If going through the url encoding process is the current standard, I will proceed with the PR work.

Indeed it has the same problem in basic qbit UI

**Comment by m4ximuel** [comment]
@ArabCoders If so, I have to reject the features you want. Unnecessary encoding and decoding operations can damage the original. This is very important.

![rename title](https://user-images.githubusercontent.com/54457152/115820079-165ab080-a43b-11eb-9a77-aea8a1562175.png)
We can consider adding functionality to the 'rename modal'.

**Comment by ArabCoders** [comment]
> @ArabCoders If so, I have to reject the features you want. Unnecessary encoding and decoding operations can damage the original. This is very important.
> 
> 
> 
> ![rename title](https://user-images.githubusercontent.com/54457152/115820079-165ab080-a43b-11eb-9a77-aea8a1562175.png)
> 
> We can consider adding functionality to the 'rename modal'.

Thanks. may i ask what kind of damage you are thinking might happen? its for visual display only not for renaming the actual disk files.

**Comment by m4ximuel** [comment]
@ArabCoders In rare cases, the content name may have a name that resembles a URL code. I don't come up with a suitable sample right now, but I had struggled quite a bit with related issues.
The most serious thing about this problem is that the user is not immediately aware that the original has been corrupted.

**Comment by ArabCoders** [comment]
@m4ximuel it would greatly appreciate it if you could include an option hidden in say VueTorrent options to do it, and it's off by default for all users.

And Thank you.

**Comment by WDaan** [comment]
@m4ximuel I like this approach

**Comment by m4ximuel** [comment]
![isuri](https://user-images.githubusercontent.com/54457152/115971951-90e41700-a586-11eb-8058-d495a6af3d38.gif)

#244 
In the past, there used to be a lot of human error in the title for torrents, but now most of the time it doesn't exist. That's why we don't want to include the ability to do it automatically in terms of performance. If the case is 'universal' rather than 'special case', we can positively consider adding functionality. but not now. sorry about that.
