### ISSUE TITLE
Saved Settings after logout

### ISSUE THREAD

**Issue by eldervamp** [WDaan/VueTorrent#295]
Hi,

Is there a way for changed settings to stay saved after logout? Like the VueTorrent / General / Pagination or Dashboard? After I logout and then logon, settings have returned to default. My setup to use VueTorrent is by Tools->Preferences->WebUI enable Use alternative WebUI. Not sure if using that method is why my custom settings are not being saved.

**Comment by WDaan** [comment]
Custom settings are saved in localstorage. Some people have configured their browser to clear them after they close.

Perhaps this is the issue here? Or do I misunderstand the problem?

**Comment by eldervamp** [comment]
Oh that explains it. I thought VueTorrent webui had a saved settings file on the servers end where qbittorrent webui is running. I didn't know the changed settings was stored on the localstorage cache in browser. Thanks for the info. Great webui, I really enjoy it :).

**Comment by WDaan** [comment]
No VueTorrent is purely a WebUI, it doesn't have permission to write to disk. I can only save things inside the browser. The plan is to move to webSQL in the future (because localstorage is not always that reliable) but I don't think that will solve this issue either.

Thanks! I'm really glad you like it 🙂
