### ISSUE TITLE
Something about search

### ISSUE THREAD

**Issue by ted423** [WDaan/VueTorrent#306]
Readed https://github.com/WDaan/VueTorrent/issues/250

as a torrent named Key and Peele S03 1080p BluRay REMUX AVC TrueHD.5.1-EPSiLON
but the group name “EPSiLON” is on the last but can't be searched

**Comment by IevgenSobko** [comment]
@ted423  That is great that you found our initial discussion about filtering. And I think you already got why you can't find expected torrent.
I thought noone needs matches which starting at position past 25.
We use [fuse.js](https://fusejs.io/api/options.html#threshold) with `threshold` 0.25 which means with default `distance` value of 100 it will search for matches which starting position is only in first 100*0.25=25 letters.
https://github.com/WDaan/VueTorrent/blob/master/src/views/Dashboard.vue#L247
@WDaan we tuned this property last time by my request because I had too much matches.
How about  we stop using `fuse.js` because  I actually have severe performance issue with it.
My torrent list is under 500 torrents and I am getting some response from UI(on type text) only after about 3-5 seconds(depends on devices). Also see MacBook gets very hot very fast if I leave VueTorrent tab opened with some filter. This issue is even worse on mobile devices(phone, tablet).

**Comment by ted423** [comment]
At present, I have 950 torrents, and the search will be obviously stuck
But in using this webui will not
https://github.com/CzBiX/qb-web

However, I do not know the specific implementation and if it  has some problem

**Comment by IevgenSobko** [comment]
@WDaan lets switch to complete match instead fuzzy for next release.
It should dramatically increase performance as well as increase position of match in a string.
