### ISSUE TITLE
Where are the Incoming port settings

### ISSUE THREAD

**Issue by Efus10n** [WDaan/VueTorrent#317]
I can't find them in the UI anywhere. Maybe I'm not looking in the right places. 

My port changes frequently so it would be nice to not have to flip back to the old UI to change it.

**Comment by benyhirmansyah** [comment]
I put my comment here because @Efus10n has the same problem with me. I can tell that this is the best qbittorrent skin I've ever seen. Unfortunately, one of important option for me isn't available yet (Port used for incoming connections)

![Listening Port](https://i.imgur.com/ISSlEjq.jpg)

I often change this listening port because my VPN provider provides a free port forwarding feature for each week. So, this is important for me to allow qBittorrent's connection always stay open and maximizing its torrenting speed.

Thanks.

**Comment by proteus077** [comment]
Just wanted to comment to say I'd really appreciate this feature. Currently using the Flood UI but I prefer VueTorrent, except for the fact this setting isn't present.

**Comment by liveinaus** [comment]
I am also wanting this feature. It will be highly appreciated if someone can consider adding this to TODO list.
Thanks

**Comment by FaykoB** [comment]
im not able to find the option for forwarding either are we not able to use vue and apply the forwarded port? Do yall have a work around for the moment?

**Comment by Efus10n** [comment]
you either have to edit the QB config file with the port and then restart
QB or switch back to the stock UI and set it there. It's annoying, so I'm
not using this much right now because of it. I'd like to get around to
adding it myself and then putting in a PR but don't have the time right now.

**Comment by WDaan** [comment]
Let's see if I can pick this up, seems doable.

**Comment by illuvattarr** [comment]
would like this feature to be added to vuetorrent as well, much appreciated!
