### ISSUE TITLE
Unchecking Settings-VueTorrent-Dashboard - Properties to Display has no effect on IOS

### ISSUE THREAD

**Issue by bedub1** [WDaan/VueTorrent#464]
If you uncheck a bunch of boxes for which properties to display for torrents, then hit save, it has no effect on IOS.  Tested in both Firefox and Safari.  

It works perfectly fine on MacOS on my laptop with Firefox

**Comment by WDaan** [comment]
That is correct and by design. The mobile layout is non-configurable, so selecting/disabling properties have no effect on the mobile layout. 

(Should perhaps be explained the settings)

**Comment by bedub1** [comment]
Oh no, I can't remove all the stuff I don't want to see?  :(  If this is intentional, then yes it should be explained.  Is there a reason it's by design, and can't/won't be adjusted?

**Comment by WDaan** [comment]
Because the desktop layout is bigger and more flexible, so the components can be dynamic. As for the mobile layout, it's already hard to fit so much data in a small form factor... making it configurable as well would be very hard.

Only thing we can do is hide certain fields, but keep the blank space. And we should thoroughly explain that behaviour somewhere to not cause confusion.
