### ISSUE TITLE
File type not acceptable, only regular type accepted

### ISSUE THREAD

**Issue by despin** [WDaan/VueTorrent#5]
Hi, I wanted to test VueTorrent as interface, so I compiled it and set the interface location to qBitTorrent, but I couldn't get it to work.

I just get this message while browsing into the WebUI:
```
File type not acceptable, only regular type accepted
```

I just configure the WebUI like this:
![image](https://user-images.githubusercontent.com/16857412/78168861-fd91ee00-7426-11ea-9f55-fd0146b1049e.png)

And the directory have this hierarchy:
![image](https://user-images.githubusercontent.com/16857412/78169056-39c54e80-7427-11ea-867e-484e31114db8.png)

Thanks

**Comment by WDaan** [comment]
Hi! I'm sorry for the late response. 

What you're doing won't work at all because this isn't an alternative WEBUI. 
It's a complete separate webapp that interacts with your existing qBittorrent.
Yes, I know this isn't very practical by any means but I made this as an exercise to learn Vue.js.

I will look into how hard is this to convert this into an alternative webui for qBittorrent, when I find the time.

Thanks for understanding

**Comment by despin** [comment]
Oh now i understand. Thanks, it was also not clear to me if it was
completely separated from qBitTorrent. I don't know if I mentioned it, but
it has a great UI!

**Comment by WDaan** [comment]
Thank you very much! :)
