### ISSUE TITLE
[Feature Request] Show Detected External IP Address

### ISSUE THREAD

**Issue by tmknight** [WDaan/VueTorrent#532]
I think it would be handy information to have the external IP address displayed in the left menu area status thingy (not sure what we're calling it). 

In the QBT logs is a line that reads:
`"Detected external IP:"`

This can be parsed via CLI:
`curl -s http://[host]:[port]/api/v2/log/main | jq '.[] | select(.message|test("Detected external IP")) | .message' | awk '/Detected external IP/{print substr($NF,1,length($NF)-1)}'`

**Comment by WDaan** [comment]
Would be nifty but not sure what the real value is? As you can just Google your external IP in 2 seconds.

Also where would you put it, design wise?

**Comment by tmknight** [comment]
Definitely a "nice to have" and not essential to project success.  Benefit, since we're talking about torrenting after all, is that we have a view into VPN status.  

Seems a wealth of free spaces available here (obviously non-mobile browser):
![image](https://user-images.githubusercontent.com/548588/202025356-b6347301-d82b-4c7c-9593-e6b3cf65823b.png)

Your call - not a deal breaker for me, just sharing perceived opportunity...

**Comment by Larsluph** [comment]
And with that, you can maybe include the `connection_status` attribute just like the native WebUI to show if the server is working correctly

**Comment by TheLinuxGuy** [comment]
+1 to this request.

Definetely a nice to have feature that deluge web UI provides - I personally use this because my router is where I do my 'policy based routing' decisions. So having the IP address be checked often via curl ifconfig.me and displaying that IP value somewhere in the web ui makes me feel more secure that my firewall wasn't misconfigured or vpn policy routing (outside of the container) broke and possibly leaking my IP address.
