### ISSUE TITLE
[Feature Request] Support for RSS

### ISSUE THREAD

**Issue by Zonimi** [WDaan/VueTorrent#57]
This interface is amazing, I just miss RSS :)

**Comment by kenjibailly** [comment]
Yes please!

**Comment by WDaan** [comment]
I've though about this issue for a long time and I'm afraid I must dissapoint you.

I don't really see the benefit of this when things like Sonarr/Radarr/... exist.
I also don't want to spend hours creating & maintaining a feature I don't really find usefull myself.

I hope you guys understand.

Feel free to convince me otherwise :slightly_smiling_face:

**Comment by Shutruk** [comment]
> I've though about this issue for a long time and I'm afraid I must dissapoint you.
> 
> I don't really see the benefit of this when things like Sonarr/Radarr/... exist.
> I also don't want to spend hours creating & maintaining a feature I don't really find usefull myself.
> 
> I hope you guys understand.
> 
> Feel free to convince me otherwise 🙂

Lots of trackers don't offer an imdb value on their RSS feeds, so most of us are left with using RSS + regex to download what we need. I would love to see this feature happening, but anyways, thanks for all the effort and the awesome job, keep it up!

**Comment by theone11** [comment]
I agree with @Shutruk. I have 2 trackers that their RSS feeds do not work with Sonarr/Radarr/...

**Comment by AyaanZaveri** [comment]
> I agree with @Shutruk. I have 2 trackers that their RSS feeds do not work with Sonarr/Radarr/...

You can try using https://github.com/CzBiX/qb-web
