### ISSUE TITLE
Feature Request: Follow the system dark mode

### ISSUE THREAD

**Issue by chuwza** [WDaan/VueTorrent#606]
Hello, now VueTorrent has "light mode" and "dark mode", can you add another "auto"? 

such as https://github.com/CzBiX/qb-web

![屏幕截图(150)](https://user-images.githubusercontent.com/30049891/212540628-fc1acc82-21d8-42f7-a9c6-b32d02d7492c.png)

**Comment by WDaan** [comment]
This has been asked a couple of times. We did have it in the past, but there were some issues with flickering. #83

In an update it was removed because you only have to set it once, and the toggle is in a convenient place, so it didn't seem worth the effort. #285

If there is great interest in this we can give it another go.
