### ISSUE TITLE
Subdirectories collapsing when changing file priorities

### ISSUE THREAD

**Issue by mylogon341** [WDaan/VueTorrent#619]
When I look at the content of a torrent, I may expand a directory to reveal season episodes, for example.
If I then change the priority of a single episode to "max" or whatever, the directory tree collapses back down again.

**Comment by Larsluph** [comment]
Thanks for reporting it! I already noticed that issue personally.
The problem here is that we reload the entire file tree when a file priority is changed.
https://github.com/WDaan/VueTorrent/blob/master/src/components/TorrentDetail/Tabs/Content.vue#L167-L169

Don't know why this issue occur as no changes has been made in this part of the code. Will need to investigate on the `open.sync` attribute.
https://github.com/WDaan/VueTorrent/blame/master/src/components/TorrentDetail/Tabs/Content.vue#L3
