### ISSUE TITLE
How to setup vuetorrent plugin in Docker

### ISSUE THREAD

**Issue by awigger** [WDaan/VueTorrent#647]
### Discussed in https://github.com/WDaan/VueTorrent/discussions/615

<div type='discussions-op-text'>

<sup>Originally posted by **fdfytr** January 21, 2023</sup>
Had to use search and dig [through links from FAQ](https://github.com/WDaan/VueTorrent/issues/27#issuecomment-683424673)

In order to install plugin in docker:
1) download zip from [releases](https://github.com/WDaan/VueTorrent/releases)
2) unzip and upload on your server (i.e. /docker/config)
3) create an additional volume in qbittorrent container
container -> /vuetorrent
host -> /docker/config/vuetorrent
4) put location for webui in settings>webui as /vuetorrent
5) save & restart the container

p.s. if you stuck at 'Unacceptable file type, only regular file is allowed' error during above steps
- stop container
- open qBittorrent/qBittorrent.conf in container settings
- change WebUI\AlternativeUIEnabled=true to WebUI\AlternativeUIEnabled=false
- restart container</div>

**Unacceptable file type, only regular file is allowed**

This issue is persistent, despite following directions perfectly, and other solutions online.
I'm using binhex on Unraid.

**Comment by tmknight** [comment]
I think this a How-To rather than issue:

1. To keep it simple, create DIR in your container at root / as /ui
2. Declare that path as volume: --volume /local/path/:/ui
3. Extract vuetorrent into /local/path/
4. Point QBT to /ui/vuetorrent
 
![image](https://user-images.githubusercontent.com/548588/218132655-e6a03d5e-35c5-4009-958d-407dbc68053d.png)

**Comment by joval-sv** [comment]
Currently, I am also using docker and using the documented volume mappings:

  * config
  * downloads

Since I do test different versions of the UI, I have come up with the 
following:

  * Download vuetorrent.zip and place it in a temporary folder
  * unzip the ZIP file, creating the vuetorrent folder
  * rename the vuetorrent folder by adding the version at the end like:
    vuetorrent-1.3.1
  * copy this folder to the folder that I use to store the docker config
    information
  * when setting up the Files location, I use: /config/vuetorrent-1.3.1

I follow the above process and I can then easily fall back to a known 
good version if he latest version is also giving me problems, or if I 
want to see how a previous version handled a particular setting. Having 
multiple versions of the UI is not a bad thing, and it's easy to switch 
and know which version you are using if the folder also has the version.

**Comment by tmknight** [comment]
I suggest this be moved to Discussions Q&A

**Comment by WDaan** [comment]
Thanks @tmknight! Things like this should definitely be moved to a discussion instead.

Also if you're having issues installing this into a container, you could always use hotio's pre-build one.

**Comment by mattish91** [comment]
> Thanks @tmknight! Things like this should definitely be moved to a discussion instead.
> 
> Also if you're having issues installing this into a container, you could always use hotio's pre-build one.

Worth to add to this is that if you use this on hotio's qbittorrent, you will need to run `chown hotio:hotio /pathto/VueTorrent`
