### ISSUE TITLE
Adding a new torrent (Magnet) by clicking on the URL button to paste, outputs API error.

### ISSUE THREAD

**Issue by Samillion** [WDaan/VueTorrent#666]
![image](https://user-images.githubusercontent.com/17427046/219970715-533bad6b-93ca-4c13-b6df-9f0804956445.png)

If you try to paste a magnet link using the button, it outputs an API error.

Raspberry Pi:
- qBittorrent 4.2.5
- VueTorrent 1.3.1

Windows 10:
- Firefox v110.0
- Brave v1.48.167
- Edge v110.0.1587.50

![image](https://user-images.githubusercontent.com/17427046/219970693-959a1794-b467-4c96-96cb-4e619ff06d8e.png)

**Comment by Larsluph** [comment]
If this button doesn't work, it means that your browser isn't using a secure context.
Basically a context is considered secured if the URL uses HTTPS or is localhost.

If you want to make VueTorrent a secure context, you will have to:
- Generate a self-signed certificate on your qbit server
- Switch to the base WebUI
- Go in the WebUI's settings, WebUI > Web User Interface > Use HTTPS instead of HTTP
- Enter the generated certificate and key path
- Switch back to VueTorrent and make sure that the URL is now HTTPS, you should see a warning from your browser that the certificate is valid, that's normal it is self-signed.

![image](https://user-images.githubusercontent.com/22910497/221190578-93d924c2-2f66-4873-a58a-fa41985a1a4f.png)

Here is a link about how to create a self-signed certificate :
https://httpd.apache.org/docs/current/ssl/ssl_faq.html#aboutcerts

Related links:
Clipboard API: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard
Secure Contexts: https://w3c.github.io/webappsec-secure-contexts/

**Comment by Larsluph** [comment]
I agree that the error message isn't really helpful, I can change that.
