### ISSUE TITLE
Add restart service button or option. 

### ISSUE THREAD

**Issue by FabulousTiger** [WDaan/VueTorrent#921]
It would be nice to be able to send a
 ```systemctl restart qbittorrent-nox.service ```
with a button when it is behaving weird or to get new session stats.

**Comment by Larsluph** [comment]
I don't think it is possible as this command requires root privileges.
However, if you run qBittorrent as a docker container, you can configure your container to restart automatically unless stopped, and then shutdown qBittorrent with the shutdown button at the bottom of the navbar which will restart the container.

The only solution I can think of ATM is setting up a cron job that will periodically check your service, and start it if it is down so that you can shut it down and it will restart without you connecting to your host.
